package io.github.tax1116.fixedwidthcodec.processor

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.getAnnotationsByType
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo
import io.github.tax1116.fixedwidthcodec.annotations.Record
import io.github.tax1116.fixedwidthcodec.runtime.AbstractRecordMapper
import java.nio.charset.Charset
import javax.annotation.processing.Generated

/**
 * KSP processor that generates a fixed-width record mapper for every class
 * annotated with [Record].
 *
 * Only properties declared in the primary constructor are considered.
 * Properties declared in the class body are ignored.
 */
class FixedWidthRecordMapperProcessor(private val codeGenerator: CodeGenerator, private val logger: KSPLogger) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotatedClasses = resolver.getSymbolsWithAnnotation(Record::class.java.canonicalName)
            .filterIsInstance<KSClassDeclaration>()

        annotatedClasses.forEach { annotatedClass ->
            generateImplementation(annotatedClass)
        }

        return emptyList()
    }

    @OptIn(KspExperimental::class)
    private fun generateImplementation(declaration: KSClassDeclaration) {
        val className = "${declaration.simpleName.asString()}$RECORD_POSTFIX"
        val packageName = declaration.packageName.asString()
        val typeSpec = TypeSpec.objectBuilder(className)
            .addKdoc("Generated by fixed-width-codec.")
            .addAnnotation(Generated::class)
            .superclass(AbstractRecordMapper::class)
            .addProperty(
                PropertySpec.builder("charset", Charset::class)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer(
                        "%T.forName(%S)",
                        Charset::class,
                        declaration.getAnnotationsByType(Record::class).first().charset,
                    ).build(),
            )
        val props = getPrimaryConstructorProperties(declaration)

        val serializeFunc = SerializeFunctionBuilder.build(declaration, props)
        val deserializeFunc = DeserializeFunctionBuilder.build(declaration, props)

        typeSpec.addFunctions(listOf(serializeFunc, deserializeFunc))

        val fileSpec = FileSpec.builder(packageName, className)
            .addType(typeSpec.build())
            .indent("    ")
            .build()

        fileSpec.writeTo(codeGenerator, Dependencies(false, declaration.containingFile!!))
    }

    private fun getPrimaryConstructorProperties(declaration: KSClassDeclaration): List<KSPropertyDeclaration> {
        val props = declaration.getAllProperties().associateBy { it.simpleName.asString() }
        val params = declaration.primaryConstructor?.parameters
            ?: throw IllegalStateException("Primary constructor not found on ${declaration.simpleName.asString()}")

        return buildList {
            params.forEach { param ->
                props[param.name!!.asString()]?.let { property ->
                    add(property)
                }
            }
        }
    }

    companion object {
        const val RECORD_POSTFIX = "RecordMapper"
    }
}
